In [4]:
from __future__ import print_function

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV

np.random.seed(0)

# Read data from Titanic dataset.
titanic_url = ('https://raw.githubusercontent.com/amueller/'
               'scipy-2017-sklearn/091d371/notebooks/datasets/titanic3.csv')
data = pd.read_csv(titanic_url)

# We will train our classifier with the following features:
# Numeric Features:
# - age: float.
# - fare: float.
# Categorical Features:
# - embarked: categories encoded as strings {'C', 'S', 'Q'}.
# - sex: categories encoded as strings {'female', 'male'}.
# - pclass: ordinal integers {1, 2, 3}.

# We create the preprocessing pipelines for both numeric and categorical data.
numeric_features = ['age', 'fare']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

categorical_features = ['embarked', 'sex', 'pclass','boat']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression(solver='lbfgs'))])

X = data.drop('survived', axis=1)
y = data['survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X)
clf.fit(X_train, y_train)
print("model score: %.3f" % clf.score(X_test, y_test))

      pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN
...       ...    ...    ...     ...       ...      ...      ...  ...    ...
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN

                            home.dest
0                        St Louis, MO
1     Montreal, PQ / Chesterville, ON
2     Montreal, PQ / Chesterville, ON
3     Montreal, PQ / Chesterville, ON
4     Montreal, PQ / Chesterville, ON
...                               ...
1304                              NaN
1305                              NaN
1306                              NaN
1307                              NaN
1308                              NaN

[1309 rows x 13 columns]
model score: 0.954